### ISSUE TITLE
GenerateExternalSqlTableCreateOrAlterCommand does not alter - only create

### ISSUE THREAD

**Issue by chriswue** [Azure/azure-kusto-dotnet#10]
Unlike the name implies the `GenerateExternalSqlTableCreateOrAlterCommand` function issues a '.create' and not a `.create-or-alter` command. Currently we work around this by string replacing '.create external table' with `.create-or-alter external table` in the command.
Would be nice to fix this correctly. I would submit a PR since it seems an easy fix but the SDK doesn't seem to be open-source.

**Comment by slavikn84** [comment]
Thanks for reporting. Checking.

**Comment by slavikn84** [comment]
Ack, this is a bug.
We'll fix, and will release a new SDK version in January.
I'll update here when we do.

**Comment by slavikn84** [comment]
@chriswue, the bug is fixed in the latest SDK version.
Again, thanks for reporting.
