### ISSUE TITLE
GenerateExternalAzureStorageTableCreateOrAlterCommand creates invalid partition by definition

### ISSUE THREAD

**Issue by chriswue** [Azure/azure-kusto-dotnet#11]
When passing a `partitionList` it will generate a `partition by` clause like this: `partition by p1, p2, p3, ...` which is not accepted by ADX. The partitions need to be enclosed in parenthesis like this `partition by (p1, p2, p3, ...)`

**Comment by slavikn84** [comment]
Checking.

**Comment by slavikn84** [comment]
We've already fixed this bug in the latest SDK (released earlier this month).
Please upgrade to the latest SDK version, and it will work for you.

**Comment by slavikn84** [comment]
Ack, this is a bug.
We'll fix, and will release a new SDK version in January.
I'll update here when we do.

**Comment by slavikn84** [comment]
@chriswue, the bug is fixed in the latest SDK version.
Again, thanks for reporting.
