### ISSUE TITLE
GenerateExternalAzureStorageTableCreateOrAlterCommand_Internal doesn't issue a create-or-alter command

### ISSUE THREAD

**Issue by chriswue** [Azure/azure-kusto-dotnet#12]
Basically all convenience functions in the `CslCommandGenerator` class that follow the `GenerateXYZCreateOrAlterCommand` naming convention generate a `.create-or-alter` command except `GenerateExternalAzureStorageTableCreateOrAlterCommand_Internal` (which all the external storage table create commands boil down to) that either outputs a `.create` (default) or an `.alter` (when the `alter` parameter is set to true). This breaks consistency and also makes it less useful since you cannot generate a `.create-or-alter` statement which is arguably the most useful command when dealing with schema management.

**Comment by slavikn84** [comment]
Ack.
We'll fix, and will release a new SDK version in January.
I'll update here when we do.

**Comment by slavikn84** [comment]
@chriswue, the bug is fixed in the latest SDK version.
Again, thanks for reporting.
