### ISSUE TITLE
Package is constantly writing to console

### ISSUE THREAD

**Issue by johan-ksat** [Azure/azure-kusto-dotnet#13]
The package Microsoft.Azure.Kusto.Data is clogging up the console with tons of logs. We are using console logging provider and stores everything that's written to console. The package doesn't seem to use a logger, but rather more directly writing to console with Console.WriteLine or similar, so changing log level doesn't help.

Here's a screenshot from the logging in VS Code, the two upper logs (starting with P.*) are from the kusto package while the other two (tagged with info) are our own logs.

![image](https://user-images.githubusercontent.com/115155180/211334389-1d12a140-f235-426e-b0b8-80c09f447b6f.png)

**Comment by chriswue** [comment]
I cannot confirm this, we don't see these logs in our console. We do use the `Microsoft.Extensions` packages `DependencyInjection` and `Logging` to wire everything up - maybe that makes a difference?

**Comment by johan-ksat** [comment]
Adding this got rid of most of the logging, which is good enough for now:

`TraceSourceManager.SetTraceVerbosityForAll(TraceVerbosity.Error);`

But I still get logs from "Tweaks" when connecting to ADX:

![image](https://user-images.githubusercontent.com/115155180/213195884-d83118b5-0ddb-4509-bb4d-1dc8e4793c61.png)

**Comment by chriswue** [comment]
I guess some of this is documented here but I haven't really played around with it: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/api/netfx/controlling-tracing
