### ISSUE TITLE
Exception when used in Blazor

### ISSUE THREAD

**Issue by torshy** [Azure/azure-kusto-dotnet#2]
Hi,
I've created a kusto client with AvaloniaUI, and it fails when running in the browser with the webassembly target. 

This is with the 10.0.0-preview version. The previous version fails with a slightly different exception, yet the same underlying issue. 

![image](https://user-images.githubusercontent.com/807245/154948981-8a8ead14-016e-4ef9-bc3f-5e9bc96857a4.png)

Might be more issues and ultimately that it won't work at all, but it would be really nice to be able to target Windows, Linux, Mac and the Web with the same code.

**Comment by yogilad** [comment]
We did not officially support Blazor.
You can try the new SDK version which is released in .net6 as weel.
Perhaps this compatibility issue is resolved there.
