### ISSUE TITLE
Provide more utilities or options for escaping data interpolated into queries

### ISSUE THREAD

**Issue by NoTuxNoBux** [Azure/azure-kusto-dotnet#22]
There is already a mechanism in place for using query parameters through the SDK, which is based on the `declare query_parameters` construct, if I understand correctly, which works as expected, but there appear to be some gaps where no (documented) utilities exist to escape and the existing parameters don't work where we have to resort to .NET interpolation with potential security risks:

* Parameters passed to 'set stored query result' and variants, such as the stored query result name: `.set stored_query_result {escapedName} with (previewCount = 1, expiresAfter = {expiresAfterMinutes}m)`
* Extent tags (strings) in various places, such as inline ingestion. `.append SomeTable with tags('[{myEscapedString}]') <| ...`
* [The inline ingestion data format (with or without brackets)](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/data-ingestion/ingest-inline#ingest-with--syntax), which is entirely different from the streaming or file ingestion format (which just uses e.g. JSON and can rely on existing JSON .NET utilities).
* Table names.
* ...

The third one is especially relevant since tags cannot be passed when ingesting through streaming (#21) and other means of ingestion, such as through files, can be less appropriate for applications generating the data on demand.

**Comment by yogilad** [comment]
Query parameters are only supported with KQL Queries.
Commands (anything that starts with a dot '.') do not have this mechanism implemented.

**Comment by NoTuxNoBux** [comment]
I understand, but I actually meant not just 'support query parameters' for all of these, but alternatively perhaps also expose some .NET methods that can aid with escaping when interpolating other things into queries.

Currently I'm just interpolating by using C# interpolation, but if I want to base values on user input, I'm left to do escaping myself, which is asking for an injection security problem sooner or later.
