### ISSUE TITLE
Support System.Text.Json

### ISSUE THREAD

**Issue by ThiemeNL** [Azure/azure-kusto-dotnet#23]
The Microsoft.Azure.Kusto.Data library is using Newtonsoft for json serialization. Please make it configurable to choose your own serializer like they have done with cosmosdb client lib.

I would like to use System.Text.Json.

**Comment by yogilad** [comment]
@ThiemeNL , the inner workings of Kusto.Data is at the digression of Microsoft.
If there's a specific issue with Newtonsoft you wish to raise **perhaps** we can address it, but an outright request for replacing a dependency is not something we can accomodate.

**Comment by ThiemeNL** [comment]
Hi @yogilad its just because all our json convertors are System.Text.Json based and the documentation about how the call the api yourself using a plain http post does not exists (#16) And that the source code is closed doesn't help aswell #20
