### ISSUE TITLE
azure kusto boolean datatype in SDK handled as sbyte

### ISSUE THREAD

**Issue by cplankl** [Azure/azure-kusto-dotnet#24]
Hey there,

In our project we use the `ICslQueryProvider` together with the `ExecuteQueryAsync` method. I have a query that also returns a boolean value. My example code looks as following:

```
var myQuery = """
                      datatable (MyString:string, MyBool:bool)
                      [
                          "", false,
                          "", true
                      ]
                      """;

var dataReader = await _queryProvider.ExecuteQueryAsync(myQuery, ...)
```

To retrieve the rows and columns of the result set I iterate the datareader like this:

```
while (dataReader.Read())
{
     var r = new
     {
          MyString = dataReader.GetString(0),
          MyBoolean = dataReader.GetBoolean(1) //this crashes due to conversion exception
     };
}
```

Unfortunately, the datatype of MyBoolean cannot be parsed as the exception message says: 
`System.InvalidCastException: Unable to cast object of type 'System.SByte' to type 'System.Boolean'`.

I know that there are workarounds to bypass this limitation. But I wonder why this is converted to an SByte instead handling it as a boolean value.

**Comment by yogilad** [comment]
Will be released with version v12.0.0 (not preview)

**Comment by AsafMah** [comment]
12.0.0 released - closing.

**Comment by thebarrettlo** [comment]
Hi, I was having the same issue and found this thread. We were using version 11.3.5, so I upgraded our Kusto NuGet packages to 12.0.1 and bools are still being treated as SByte. Our use case is loading the `IDataReader` into a `DataTable` using `DataTable.Load(IDataReader)`.

**Comment by cppxaxa** [comment]
I checked with 12.2.3, boolean is still treated as SByte
