### ISSUE TITLE
[Microsoft.Azure.Kusto.Ingest/ Microsoft.Azure.Kusto.Data] Please upgrade Microsoft.Identity.Client to 4.61.3

### ISSUE THREAD

**Issue by arsamigullin** [Azure/azure-kusto-dotnet#32]
Both Microsoft.Azure.Kusto.Ingest and Microsoft.Azure.Kusto.Data of latest version (12.2.3) are referring to Microsoft.Identity.Client of 4.60.3 package. Our system is required to use Microsoft.Identity.Client of 4.61.3, so we are now getting package downgrade error

**Comment by AsafMah** [comment]
Is there a typo here perhaps? You wrote 4.60.3 twice

**Comment by arsamigullin** [comment]
Thank you just updated. So, I meant update to Microsoft.Identity.Client of 4.61.3

**Comment by AsafMah** [comment]
We will probably upgrade it in the next minor version.

As a temporary workaround, you can try adding 'NoWarn' as follows:
<PackageReference Include="Microsoft.Identity.Client" Version="4.60.3" NoWarn="NU1605" />
 
And then add a binding redirect in his application project App.config file, from range 0.0.0.0-4.61.3 to version 4.60.3.

**Comment by AsafMah** [comment]
Version 12.2.4 was released with this dep, closing.
