### ISSUE TITLE
Request: Include .update command in CslCommandGenerator

### ISSUE THREAD

**Issue by jeromekol** [Azure/azure-kusto-dotnet#33]
The newly introduced [.update command](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/update-table-command) is missing from the CslCommandGenerator class. Is it planned to include that as well in the Microsoft.Azure.Kusto.Data nuget and if yes, is there an ETA?
Thank you

**Comment by shanisolomon** [comment]
Hi @jeromekol,

We do intend to include the new .update command in the CslCommandGenerator class, there's currently no official ETA (probably in the next month)

Thanks,
Shani

**Comment by AsafMah** [comment]
Released as part of 12.2.4
