### ISSUE TITLE
KustoClientRequestCanceledByUserException should inherit from OperationCancelledException

### ISSUE THREAD

**Issue by Emeka-MSFT** [Azure/azure-kusto-dotnet#34]
This is related to the following issue: #30.

By [convention][1], `KustoClientRequestCanceledByUserException` should inherit from [OperationCancelledException][0].
* It appears to inherit from `KustoClientException` -> `KustoException` -> `Exception`.
* By not inheriting from [OperationCancelledException][0], calling code will not be able to reuse catch-blocks that gracefully handle the user cancellation scenarios.

**Side Note:**
* Please review other instances and consider addressing them as well.
* Given that `KustoClientRequestCanceledByUserException` is a customer facing exception, also consider adding a doc for it.

[0]: https://learn.microsoft.com/en-us/dotnet/api/system.operationcanceledexception?view=net-8.0
[1]: https://blog.stephencleary.com/2022/03/cancellation-3-detecting-cancellation.html

**Comment by ohadbitt** [comment]
Hi
Kusto decided to (almost) only throw KustoException type, so as for users (and ourselves) to be able to handle it together. 
As for the side note - it is a new exception - we do need to document it.

**Comment by Emeka-MSFT** [comment]
> Kusto decided to (almost) only throw KustoException type, so as for users (and ourselves) to be able to handle it together.

By design, operation-cancelled-exception is a special case; i.e. it is the/that exception to the rule (of single base exception).
Therefore, please reconsider; this is a wrong decision.

**More Data/Justification:**
If every component/library decides to create their own user-cancelled-exception (which doesn't derive from OperationCancelledException), then async pattern will be broken. All code will have to:
1. understand the dependency chain of all sdks/libraries that they reference/consume.
2. ensure that they handle all possible (one-off) user-cancelled-exception types (in there catch block)
3. expand test matrix to ensure that all user-cancelled-exception corner-cases are capture.
4. devote time to always carefully review any update to these nuget packages, in case there are changes.

**Summary:**
This decision 
(a) breaks c# convention, and 
(b) doesn't consider consumer/consumption pattern, and 
(c) prioritizes sdk-team's convenience over customer products complexity and cost of maintenance.
