### ISSUE TITLE
Upgrade from 11 to 12.2.3 Runs into OOM issues

### ISSUE THREAD

**Issue by mnguyen36** [Azure/azure-kusto-dotnet#39]
We're looping over an array of ids and retrieving a query for the array i.e.

for (query in queries) {
var kustoValue = _kustoClientQuery.ExecuteQuery(quer);
while (kustoValue.Read()) 
{
   dostuff(kustoValue.GetString(0));
{

Reverting only the package change back to 11 fixes the problem but we have a requirement to migrate to 12.2.3+.

**Comment by AsafMah** [comment]
We haven't managed to recreate this nor have gotten any other reports for this issue, so we'll need more details to help you.

What query are you running?  
How long does it run for?
How big is the data you're getting from it?
How much memory do you see your process taking on version 11?
Can you try other versions between 11 and 12.2.3 and see in which version does it start to break?

**Comment by AsafMah** [comment]
I'm closing due to a lack of reply.

Feel free to comment if you have a response and I'll re-open.
