### ISSUE TITLE
Default CslType for `decimal` changed in 12.2.4

### ISSUE THREAD

**Issue by SaifAqqad** [Azure/azure-kusto-dotnet#42]
It seems the default `CslType` mapping for `decimal` was changed from `System.Decimal` in 12.2.3 to `SqlDecimal` in 12.2.4.

If this change was intended and not a bug, then it needs to be added to the release notes.

**Comment by AsafMah** [comment]
Thank you.

We will check about this change.

Can you show us where this has affected your usage of the SDK?

**Comment by SaifAqqad** [comment]
I map the values to a model before using them, the mapping used `Convert.ChangeType` which doesn't support the `SqlDecimal` type.

If this change will be kept as is, then I'll need to handle it differently for `SqlDecimal` columns

**Comment by yogilad** [comment]
@SaifAqqad , the change was intentional.
Which API of the service did you use that returned the altered Type?
Are you able to accommodate the change?

**Comment by SaifAqqad** [comment]
@yogilad I'm using the Query V2 API (`ExecuteQueryV2Async`)

I can add special handling for decimal columns, I already check for dynamic columns and handle them in a similar way (to convert `JObject` to `Dictionary`/`JsonObject`)

**Comment by yogilad** [comment]
Can you share a code example of where do you encounter break, so I can take it up with the team that made the change?

**Comment by SaifAqqad** [comment]
```csharp
    if (!frame.TableData.Read())
    {
        return null;
    }

    // Prepare a list of columns info
    // var columns = ...

    var records = new List<DatasetRecord>();
    var values = new object[frame.TableData.FieldCount];

    do
    {
        frame.TableData.GetValues(values);
        records.Add(new DatasetRecord
        {
            Columns = columns,
            Values = values.ToImmutableList()
        });
    } while (frame.TableData.Read());

    // map the values, etc...
```

![image](https://github.com/user-attachments/assets/c1ad88ad-f95f-47a4-93cb-641792b85583)

In this case, it used to return a simple `System.Decimal` for the second column, the mapping logic (not included here) uses `Convert.ChangeType` which supports `System.Decimal` but not `SqlDecimal`

**Comment by AsafMah** [comment]
We released 12.2.6 today that reverts this, can you check with your use case?

**Comment by SaifAqqad** [comment]
Can confirm `decimal` values are now returned as `System.Decimal` on 12.2.6

**Comment by AsafMah** [comment]
Thank you!

Please know that we might include this change in the next major version though.
