### ISSUE TITLE
Workload Identity support

### ISSUE THREAD

**Issue by Costo** [Azure/azure-kusto-dotnet#48]
Hi,

Is Workload Identity supported with this library? I found extension methods for User Assigned Identity and System Assigned Identity but not for using Workload Identity in k8s.
It seems that this is supported in the [Go library](https://github.com/Azure/azure-kusto-go/blob/master/README.md#using-a-k8s-workload-identity)

Thanks

**Comment by AsafMah** [comment]
We don't plan to add it for now, since as you found by yourself, you can use the TokenCredential Auth for that.

In Go, it was a contribution that we didn't mind adding.

Soon we will publish a doc that goes in detail for Auth methods.
