### ISSUE TITLE
Request: Better timeout control in `IngestFrom{...}Async`

### ISSUE THREAD

**Issue by palhal** [Azure/azure-kusto-dotnet#51]
I'm currently using the `IKustoIngestClient.IngestFromDataReaderAsync` method, but when I deployed the code to production, the call wouldn't return (actually throw a `SocketException`) until 20 minutes had passed. After a bit of troubleshooting, I found that the reason was that I had enabled IP whitelisting on the cluster. 

I tried setting `QueueOptions.NetworkTimeout` to 10 seconds and `MaxRetries` to 0, but it didn't change anything. This option is also not available for streaming ingestion.

20 minutes (operating system default?) is too long to wait for connection timeouts in my case, therefore I propose the following improvements:

####  Proposal 1:
New `IngestClientOptions.Timeout` property, similar to [HttpClient.Timeout](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-8.0).

#### Proposal 2:
New `cancellationToken`  parameter in `IngestFrom{...}Async`, similar to [HttpClient.SendAsync](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.sendasync?view=net-8.0#system-net-http-httpclient-sendasync(system-net-http-httprequestmessage-system-threading-cancellationtoken)).

**Comment by yogilad** [comment]
Hi @palhal ,

Try passing IngestClientOptions **instead** and configuring it such that storage retries (upload) and service calls are limited to 2 or 3 attempts.

**Comment by yogilad** [comment]
So, the service is making 3 attempts (inital + 2 additional tries) with 1 second delay.
Certain TCP errors, and specially the one below take time to occur because the client effectively times out on some part of the TCP. 
All in all, the time makes sense given the scenario you mentioned above.

```
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by palhal** [comment]
> Certain TCP errors, and specially the one below take time to occur because the client effectively times out on some part of the TCP. 

Yes, hence my request for some additional control. I've updated my original post with links that describe the behavior I would like.

**Comment by yogilad** [comment]
Kusto is working on V2 version of the ingest client which will include support of cancelation tokens.
I believe it will be released sometime around Q1 2025.

**Comment by AsafMah** [comment]
Closing for now, thanks.
